global:
  scrape_interval: 15s  # Coleta de métricas a cada 15 segundos para todos os jobs

scrape_configs:
  - job_name: 'prometheus'  # Coleta de métricas do Prometheus
    static_configs:
      - targets: 
          - 'localhost:9090'  # Alvo é o próprio Prometheus

  - job_name: 'mysqld_exporter'  # Coleta de métricas do MySQL
    static_configs:
      - targets: 
          - '192.168.100.8:9104'  # Alvo é o MySQL Exporter
